function askToShare(){if($.cookie("askShareSite")!==undefined){return;}else{$.cookie("askShareSite",true,{expires:1000,path:'/'});}
$("#sms-share-fb").click(function(){ga('send',{hitType:'event',eventCategory:'growth',eventAction:'share-fb',eventLabel:'SMS'});$("#shareModal").modal("hide");});$("#sms-share-twitter").click(function(){ga('send',{hitType:'event',eventCategory:'growth',eventAction:'share-twitter',eventLabel:'SMS'});$("#shareModal").modal("hide");});$("#sms-share-gplus").click(function(){ga('send',{hitType:'event',eventCategory:'growth',eventAction:'share-gplus',eventLabel:'SMS'});$("#shareModal").modal("hide");});$("#sms-maybe-later").click(function(){ga('send',{hitType:'event',eventCategory:'growth',eventAction:'maybe-later',eventLabel:'SMS'});$("#shareModal").modal("hide");});$("#shareModal").modal("show");ga('send',{hitType:'event',eventCategory:'growth',eventAction:'show-share-modal',eventLabel:'SMS'});}
function giveDiscount(){if($.cookie("DidGiveDiscount_swift10")!==undefined){return;}else{$.cookie("DidGiveDiscount_swift10",true,{expires:1000,path:'/'});}
$("#discountModal").modal("show");ga('send',{hitType:'event',eventCategory:'marketing',eventAction:'show-discount-modal',eventLabel:'BMB'});var code=$("#discount-code").text();$.cookie("last_discount",code,{expires:1000,path:'/'});$("#discountBB a").click(function(){ga('send',{hitType:'event',eventCategory:'marketing',eventAction:'click-buy',eventLabel:'BMB'});});}
function timeDiff(a,b){return Math.round((b-a)/(1000));}
$(document).ready(function(){if($.cookie("MONKEY_NO")!==undefined){return;}
var pageCount=parseInt($.cookie("PAGE_COUNT"));if(isNaN(pageCount)){pageCount=0;}
pageCount+=1;$.cookie("PAGE_COUNT",pageCount.toString(),{expires:1000,path:'/'});var category=$("#mtag").attr("category");var categoryPageCount=0;if(category!==undefined){var categoryKey=category.toUpperCase();categoryPageCount=parseInt($.cookie(categoryKey));if(isNaN(categoryPageCount)){categoryPageCount=0;}
categoryPageCount+=1;$.cookie(categoryKey,categoryPageCount.toString(),{expires:1000,path:'/'});ga('send',{hitType:'event',eventCategory:category+' - '+categoryPageCount.toString(),eventAction:'viewCategory',eventLabel:'SMS'});}
var now=new Date();var firstSession=new Date($.cookie("FIRST_SESSION"));if(isNaN(firstSession)){firstSession=now;$.cookie("FIRST_SESSION",now.toString(),{expires:1000,path:'/'});}
var lastSession=new Date($.cookie("LAST_SESSION"));if(isNaN(lastSession)){lastSession=now;}
$.cookie("LAST_SESSION",now.toString(),{expires:1000,path:'/'});ga('send',{hitType:'event',eventCategory:'pageCount'+pageCount.toString(),eventAction:'load',eventLabel:'SMS'});if(pageCount>=7&&timeDiff(firstSession,now)>5*60){askToShare();return;}
if(category=="learn-to-code"&&categoryPageCount>=3){return;}});